import "server-only";

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Edge } from "@xyflow/react";

const ROOT = process.cwd();
const FLOW_MAP_PATH = path.join(ROOT, "data", "atlas-flow-map.json");
const FLOW_VIEWS = ["all", "atlas", "borrower", "investor"] as const;
export type FlowStatus = "core" | "review" | "external" | "decision";
export type FlowView = (typeof FLOW_VIEWS)[number];
export interface FlowRecord { id: string; title: string; lane: string; summary: string; href?: string; notes: string; status: FlowStatus; position: { x: number; y: number }; actor: string; phase: string; output: string; goal: string; gates: string[]; viewTags: FlowView[]; }
export interface AtlasFlowMapRecord { records: FlowRecord[]; edges: Edge[]; updatedAt: string; }
export const defaultFlowRecords: FlowRecord[] = [
{ id: "deal-intake", title: "Deal Intake", lane: "Atlas", summary: "Create the deal, set state and structure, and lock the first workflow assumptions.", href: "/cases/new", notes: "Turicum LLC turns raw deal facts into the operating plan.", status: "core", position: { x: 40, y: 60 }, actor: "Turicum LLC ops", phase: "Origination", output: "Deal profile and workflow plan", goal: "Start the file with enough structure to drive borrower, investor, and legal lanes.", gates: ["State selected", "Deal shape set", "Capital assumptions recorded"], viewTags: ["all", "atlas"] },
{ id: "intake-workspace", title: "Borrower Intake Workspace", lane: "Borrower", summary: "Assign borrower forms, collect documents, and track packet completion.", href: "/cases", notes: "This is the borrower collection console before promotion can complete.", status: "core", position: { x: 220, y: 240 }, actor: "Turicum LLC ops + borrower", phase: "Collection", output: "Borrower packet and document readiness", goal: "Collect the borrower facts and documents Turicum LLC needs before underwriting and investor take-up are final.", gates: ["Borrower contact saved", "Required forms assigned", "Supporting docs requested"], viewTags: ["all", "borrower", "atlas"] },
{ id: "borrower-portal", title: "Borrower Portal", lane: "Borrower", summary: "Borrower completes forms and sees what is pending or ready for signature.", href: "/portal", notes: "External borrower lane.", status: "external", position: { x: 400, y: 240 }, actor: "Borrower", phase: "Submission", output: "Completed packet and signer readiness", goal: "Give the borrower one guided surface for forms, documents, and upcoming signatures.", gates: ["Portal shared", "Assigned forms submitted", "Borrower questions resolved"], viewTags: ["all", "borrower"] },
{ id: "borrower-property-validation", title: "Borrower + Property Validation", lane: "Atlas", summary: "Validate the borrower, collateral, first-call facts, and screening placeholders before investors see the deal.", href: "/cases", notes: "Internal underwriting checkpoint.", status: "review", position: { x: 580, y: 60 }, actor: "Turicum LLC underwriting", phase: "Validation", output: "Validated borrower/property package", goal: "Clear the underwriting case before promotion, legal finalization, and funding assumptions.", gates: ["Borrower packet complete", "Supporting documents attached", "Credit/background/criminal path recorded", "Internal diligence cleared"], viewTags: ["all", "atlas"] },
{ id: "investor-promotion", title: "Investor Promotion", lane: "Investor", summary: "Package the validated deal, promote it, and confirm the final investor stack.", href: "/cases", notes: "Investor-facing packaging and take-up.", status: "decision", position: { x: 760, y: 420 }, actor: "Capital markets + investors", phase: "Placement", output: "Final investor count and structure", goal: "Turn the validated case into an investor-backed capital structure.", gates: ["Borrower packet complete", "Validation complete", "Final investor take-up recorded"], viewTags: ["all", "investor", "atlas"] },
{ id: "investor-workspace", title: "Investor Workspace", lane: "Investor", summary: "Investor-facing operating lane for promotion, updates, and exit communication.", href: "/investor-handoff", notes: "This is the ongoing investor relationship surface.", status: "external", position: { x: 940, y: 420 }, actor: "Investors", phase: "Relationship", output: "Investor updates and visibility", goal: "Keep investors aligned from commitment through servicing and exit.", gates: ["Promotion summary published", "Investor structure locked", "Monthly updates prepared"], viewTags: ["all", "investor"] },
{ id: "template-selection", title: "Template Selection", lane: "Atlas", summary: "Choose the legal starting paper after the investor structure is known.", href: "/library/templates", notes: "Legal drafting starts here once the capital stack is real.", status: "core", position: { x: 760, y: 60 }, actor: "Turicum LLC legal ops", phase: "Drafting", output: "Chosen precedent on the case", goal: "Match the deal, state, and investor structure to the right starting paper.", gates: ["Investor structure confirmed", "State pack ready", "Document family chosen"], viewTags: ["all", "atlas"] },
{ id: "contract-ai-review", title: "Contract AI Review", lane: "Atlas", summary: "Run the clause and structure review before human legal approval.", href: "/cases", notes: "Turicum LLC AI review lane.", status: "review", position: { x: 940, y: 60 }, actor: "Turicum LLC AI", phase: "Review", output: "Issue list and review memo", goal: "Catch structural and clause issues before legal sign-off.", gates: ["Template chosen", "Checklist generated"], viewTags: ["all", "atlas"] },
{ id: "legal-review", title: "Legal Review", lane: "Atlas", summary: "Lawyer signs off on the paper stack before execution.", href: "/cases", notes: "Human legal document-review gate.", status: "decision", position: { x: 1120, y: 60 }, actor: "Lawyer", phase: "Approval", output: "Approved or corrected paper stack", goal: "Hold a real human approval gate before signatures and funding.", gates: ["AI review complete", "Corrections resolved", "Document review clearance granted"], viewTags: ["all", "atlas"] },
{ id: "closing-diligence", title: "Closing Diligence", lane: "Atlas", summary: "Clear title work, insurance, and tax in a separate diligence gate before execution.", href: "/cases", notes: "Title company and closing diligence gate.", status: "decision", position: { x: 1300, y: 60 }, actor: "Turicum LLC ops + title company", phase: "Approval", output: "Closing diligence clearance", goal: "Separate title, insurance, and tax diligence from document review so execution is only cleared when both gates are done.", gates: ["Title company selected", "Title work reviewed", "Insurance cleared", "Tax review cleared"], viewTags: ["all", "atlas"] },
{ id: "google-signature", title: "Google Signature", lane: "Borrower", summary: "Borrower-facing signature lane for documents that do not need notarization.", href: "/cases", notes: "Execution lane once legal and diligence are clear.", status: "external", position: { x: 1300, y: 240 }, actor: "Borrower + Turicum LLC ops", phase: "Execution", output: "Tracked e-sign request", goal: "Collect signatures after borrower, investor, legal, and diligence gates are all clear.", gates: ["Legal approval", "Closing diligence clear", "Borrower packet complete", "No notary required"], viewTags: ["all", "borrower", "atlas"] },
{ id: "funding", title: "Funding", lane: "Atlas", summary: "Set up escrow, reserve policy, and release conditions before money moves.", href: "/cases", notes: "Post-close funding control surface.", status: "core", position: { x: 1480, y: 60 }, actor: "Turicum LLC ops + escrow", phase: "Funding", output: "Escrow setup and funded status", goal: "Move from approved paper into escrow, reserves, and final funding release.", gates: ["Investor promotion complete", "Legal approval complete", "Closing diligence complete", "Execution complete", "Wire instructions ready"], viewTags: ["all", "atlas", "investor"] },
{ id: "servicing", title: "Servicing + Updates", lane: "Investor", summary: "Track monthly payments, reserve balance, and investor updates after funding.", href: "/investor-handoff", notes: "Ongoing asset management lane.", status: "core", position: { x: 1660, y: 420 }, actor: "Turicum LLC servicing + investors", phase: "Servicing", output: "Monthly investor update cadence", goal: "Keep the post-close performance story visible month by month.", gates: ["Funding complete", "Payment schedule set", "First update period prepared"], viewTags: ["all", "investor", "atlas"] },
{ id: "exit", title: "Exit / Payoff / Rollover", lane: "Investor", summary: "Run payoff, extension, refinance, sale, or rollover as an explicit workflow.", href: "/investor-handoff", notes: "Lifecycle resolution lane.", status: "decision", position: { x: 1840, y: 420 }, actor: "Turicum LLC ops + investors", phase: "Resolution", output: "Resolved or rolled deal", goal: "Make the end of the deal as structured and visible as the beginning.", gates: ["Exit path chosen", "Investor communication drafted", "Resolution docs prepared"], viewTags: ["all", "investor", "atlas"] },
{ id: "notary-branch", title: "Notary / RON", lane: "Borrower", summary: "Separate notarization branch for documents that cannot stay in the standard e-sign lane.", href: "/cases", notes: "State-specific notary path.", status: "decision", position: { x: 1480, y: 240 }, actor: "Borrower + notary", phase: "Notary", output: "RON or in-person notarization path", goal: "Break notarized paper out into its own explicit branch.", gates: ["Document needs notary", "State path chosen", "Notary provider selected"], viewTags: ["all", "borrower", "atlas"] }
];
export const defaultFlowEdges: Edge[] = [
{ id: "e1", source: "deal-intake", target: "intake-workspace", animated: false },
{ id: "e2", source: "intake-workspace", target: "borrower-portal", animated: false },
{ id: "e3", source: "borrower-portal", target: "borrower-property-validation", animated: true },
{ id: "e4", source: "borrower-property-validation", target: "investor-promotion", animated: false },
{ id: "e5", source: "investor-promotion", target: "investor-workspace", animated: false },
{ id: "e6", source: "investor-promotion", target: "template-selection", animated: true },
{ id: "e7", source: "template-selection", target: "contract-ai-review", animated: false },
{ id: "e8", source: "contract-ai-review", target: "legal-review", animated: false },
{ id: "e9", source: "legal-review", target: "closing-diligence", animated: false },
{ id: "e10", source: "closing-diligence", target: "google-signature", animated: false },
{ id: "e11", source: "closing-diligence", target: "notary-branch", animated: false },
{ id: "e12", source: "google-signature", target: "funding", animated: false },
{ id: "e13", source: "funding", target: "servicing", animated: false },
{ id: "e14", source: "servicing", target: "exit", animated: false },
{ id: "e15", source: "funding", target: "investor-workspace", animated: true },
{ id: "e16", source: "servicing", target: "investor-workspace", animated: true },
{ id: "e17", source: "exit", target: "investor-workspace", animated: true },
{ id: "e18", source: "notary-branch", target: "funding", animated: false }
];
const defaultRecordById = new Map(defaultFlowRecords.map((record) => [record.id, record]));
const defaultEdgeById = new Map(defaultFlowEdges.map((edge) => [edge.id, edge]));
function normalizeRecord(record: Partial<FlowRecord> & Pick<FlowRecord, "id" | "title" | "lane" | "summary" | "notes" | "status" | "position">): FlowRecord { const fallback = defaultRecordById.get(record.id); return { id: record.id, title: record.title, lane: fallback?.lane ?? record.lane, summary: record.summary, href: record.href ?? fallback?.href, notes: record.notes, status: record.status, position: record.position, actor: record.actor ?? fallback?.actor ?? record.lane, phase: record.phase ?? fallback?.phase ?? "Flow", output: record.output ?? fallback?.output ?? "", goal: record.goal ?? fallback?.goal ?? record.summary, gates: Array.isArray(record.gates) ? record.gates : fallback?.gates ?? [], viewTags: (() => { const currentTags = Array.isArray(record.viewTags) ? record.viewTags.filter((tag): tag is FlowView => FLOW_VIEWS.includes(tag as FlowView)) : []; const merged = Array.from(new Set([...(fallback?.viewTags ?? []), ...currentTags])); return merged.length ? merged : ["all"]; })() }; }
function buildDefaultRecord(): AtlasFlowMapRecord { return { records: defaultFlowRecords, edges: defaultFlowEdges, updatedAt: new Date().toISOString() }; }
function normalizeFlowMap(flowMap: AtlasFlowMapRecord): AtlasFlowMapRecord { const normalizedRecords = flowMap.records.map((record) => normalizeRecord(record)); const recordById = new Map(normalizedRecords.map((record) => [record.id, record])); const orderedRecords = defaultFlowRecords.map((record) => recordById.get(record.id) ?? record); const extraRecords = normalizedRecords.filter((record) => !defaultRecordById.has(record.id)); const edgeById = new Map(flowMap.edges.map((edge) => [edge.id, edge])); const orderedEdges = defaultFlowEdges.map((edge) => edgeById.get(edge.id) ?? edge); const extraEdges = flowMap.edges.filter((edge) => !defaultEdgeById.has(edge.id)); return { records: [...orderedRecords, ...extraRecords], edges: [...orderedEdges, ...extraEdges], updatedAt: flowMap.updatedAt ?? new Date().toISOString() }; }
export async function getAtlasFlowMap() { try { const raw = await readFile(FLOW_MAP_PATH, "utf8"); return normalizeFlowMap(JSON.parse(raw) as AtlasFlowMapRecord); } catch { return buildDefaultRecord(); } }
export async function saveAtlasFlowMap(input: Pick<AtlasFlowMapRecord, "records" | "edges">) { const normalized = normalizeFlowMap({ records: input.records, edges: input.edges, updatedAt: new Date().toISOString() }); const next: AtlasFlowMapRecord = { records: normalized.records, edges: normalized.edges, updatedAt: new Date().toISOString() }; await writeFile(FLOW_MAP_PATH, JSON.stringify(next, null, 2) + "\n", "utf8"); return next; }
